// Code generated by counterfeiter. DO NOT EDIT.
package kawasakifakes

import (
	"sync"

	"code.cloudfoundry.org/guardian/kawasaki"
	"code.cloudfoundry.org/guardian/kawasaki/subnets"
	lager "code.cloudfoundry.org/lager/v3"
)

type FakeSpecParser struct {
	ParseStub        func(lager.Logger, string) (subnets.SubnetSelector, subnets.IPSelector, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
	}
	parseReturns struct {
		result1 subnets.SubnetSelector
		result2 subnets.IPSelector
		result3 error
	}
	parseReturnsOnCall map[int]struct {
		result1 subnets.SubnetSelector
		result2 subnets.IPSelector
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSpecParser) Parse(arg1 lager.Logger, arg2 string) (subnets.SubnetSelector, subnets.IPSelector, error) {
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
	}{arg1, arg2})
	stub := fake.ParseStub
	fakeReturns := fake.parseReturns
	fake.recordInvocation("Parse", []interface{}{arg1, arg2})
	fake.parseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSpecParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeSpecParser) ParseCalls(stub func(lager.Logger, string) (subnets.SubnetSelector, subnets.IPSelector, error)) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = stub
}

func (fake *FakeSpecParser) ParseArgsForCall(i int) (lager.Logger, string) {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	argsForCall := fake.parseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSpecParser) ParseReturns(result1 subnets.SubnetSelector, result2 subnets.IPSelector, result3 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 subnets.SubnetSelector
		result2 subnets.IPSelector
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSpecParser) ParseReturnsOnCall(i int, result1 subnets.SubnetSelector, result2 subnets.IPSelector, result3 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 subnets.SubnetSelector
			result2 subnets.IPSelector
			result3 error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 subnets.SubnetSelector
		result2 subnets.IPSelector
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSpecParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSpecParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kawasaki.SpecParser = new(FakeSpecParser)
