// Code generated by counterfeiter. DO NOT EDIT.
package depotfakes

import (
	"sync"

	"code.cloudfoundry.org/garden"
	"code.cloudfoundry.org/guardian/rundmc/depot"
)

type FakeBindMountSourceCreator struct {
	CreateStub        func(containerDir string, privileged bool) ([]garden.BindMount, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		containerDir string
		privileged   bool
	}
	createReturns struct {
		result1 []garden.BindMount
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 []garden.BindMount
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBindMountSourceCreator) Create(containerDir string, privileged bool) ([]garden.BindMount, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		containerDir string
		privileged   bool
	}{containerDir, privileged})
	fake.recordInvocation("Create", []interface{}{containerDir, privileged})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(containerDir, privileged)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createReturns.result1, fake.createReturns.result2
}

func (fake *FakeBindMountSourceCreator) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBindMountSourceCreator) CreateArgsForCall(i int) (string, bool) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].containerDir, fake.createArgsForCall[i].privileged
}

func (fake *FakeBindMountSourceCreator) CreateReturns(result1 []garden.BindMount, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 []garden.BindMount
		result2 error
	}{result1, result2}
}

func (fake *FakeBindMountSourceCreator) CreateReturnsOnCall(i int, result1 []garden.BindMount, result2 error) {
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 []garden.BindMount
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 []garden.BindMount
		result2 error
	}{result1, result2}
}

func (fake *FakeBindMountSourceCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBindMountSourceCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ depot.BindMountSourceCreator = new(FakeBindMountSourceCreator)
