// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/guardian/kawasaki"
)

type FakeContainerApplier struct {
	ApplyStub        func(cfg kawasaki.NetworkConfig) error
	applyMutex       sync.RWMutex
	applyArgsForCall []struct {
		cfg kawasaki.NetworkConfig
	}
	applyReturns struct {
		result1 error
	}
}

func (fake *FakeContainerApplier) Apply(cfg kawasaki.NetworkConfig) error {
	fake.applyMutex.Lock()
	fake.applyArgsForCall = append(fake.applyArgsForCall, struct {
		cfg kawasaki.NetworkConfig
	}{cfg})
	fake.applyMutex.Unlock()
	if fake.ApplyStub != nil {
		return fake.ApplyStub(cfg)
	} else {
		return fake.applyReturns.result1
	}
}

func (fake *FakeContainerApplier) ApplyCallCount() int {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	return len(fake.applyArgsForCall)
}

func (fake *FakeContainerApplier) ApplyArgsForCall(i int) kawasaki.NetworkConfig {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	return fake.applyArgsForCall[i].cfg
}

func (fake *FakeContainerApplier) ApplyReturns(result1 error) {
	fake.ApplyStub = nil
	fake.applyReturns = struct {
		result1 error
	}{result1}
}

var _ kawasaki.ContainerApplier = new(FakeContainerApplier)
