// This file was generated by counterfeiter
package fakes

import (
	"sync"
	"syscall"

	"github.com/cloudfoundry-incubator/guardian/rundmc/stopper"
)

type FakeKiller struct {
	KillStub        func(signal syscall.Signal, pid ...int)
	killMutex       sync.RWMutex
	killArgsForCall []struct {
		signal syscall.Signal
		pid    []int
	}
}

func (fake *FakeKiller) Kill(signal syscall.Signal, pid ...int) {
	fake.killMutex.Lock()
	fake.killArgsForCall = append(fake.killArgsForCall, struct {
		signal syscall.Signal
		pid    []int
	}{signal, pid})
	fake.killMutex.Unlock()
	if fake.KillStub != nil {
		fake.KillStub(signal, pid...)
	}
}

func (fake *FakeKiller) KillCallCount() int {
	fake.killMutex.RLock()
	defer fake.killMutex.RUnlock()
	return len(fake.killArgsForCall)
}

func (fake *FakeKiller) KillArgsForCall(i int) (syscall.Signal, []int) {
	fake.killMutex.RLock()
	defer fake.killMutex.RUnlock()
	return fake.killArgsForCall[i].signal, fake.killArgsForCall[i].pid
}

var _ stopper.Killer = new(FakeKiller)
