// This file was generated by counterfeiter
package grootfakes

import (
	"sync"

	"code.cloudfoundry.org/grootfs/groot"
)

type FakeDependencyManager struct {
	RegisterStub        func(id string, chainIDs []string) error
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		id       string
		chainIDs []string
	}
	registerReturns struct {
		result1 error
	}
	DeregisterStub        func(id string) error
	deregisterMutex       sync.RWMutex
	deregisterArgsForCall []struct {
		id string
	}
	deregisterReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDependencyManager) Register(id string, chainIDs []string) error {
	var chainIDsCopy []string
	if chainIDs != nil {
		chainIDsCopy = make([]string, len(chainIDs))
		copy(chainIDsCopy, chainIDs)
	}
	fake.registerMutex.Lock()
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		id       string
		chainIDs []string
	}{id, chainIDsCopy})
	fake.recordInvocation("Register", []interface{}{id, chainIDsCopy})
	fake.registerMutex.Unlock()
	if fake.RegisterStub != nil {
		return fake.RegisterStub(id, chainIDs)
	}
	return fake.registerReturns.result1
}

func (fake *FakeDependencyManager) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *FakeDependencyManager) RegisterArgsForCall(i int) (string, []string) {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return fake.registerArgsForCall[i].id, fake.registerArgsForCall[i].chainIDs
}

func (fake *FakeDependencyManager) RegisterReturns(result1 error) {
	fake.RegisterStub = nil
	fake.registerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDependencyManager) Deregister(id string) error {
	fake.deregisterMutex.Lock()
	fake.deregisterArgsForCall = append(fake.deregisterArgsForCall, struct {
		id string
	}{id})
	fake.recordInvocation("Deregister", []interface{}{id})
	fake.deregisterMutex.Unlock()
	if fake.DeregisterStub != nil {
		return fake.DeregisterStub(id)
	}
	return fake.deregisterReturns.result1
}

func (fake *FakeDependencyManager) DeregisterCallCount() int {
	fake.deregisterMutex.RLock()
	defer fake.deregisterMutex.RUnlock()
	return len(fake.deregisterArgsForCall)
}

func (fake *FakeDependencyManager) DeregisterArgsForCall(i int) string {
	fake.deregisterMutex.RLock()
	defer fake.deregisterMutex.RUnlock()
	return fake.deregisterArgsForCall[i].id
}

func (fake *FakeDependencyManager) DeregisterReturns(result1 error) {
	fake.DeregisterStub = nil
	fake.deregisterReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDependencyManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	fake.deregisterMutex.RLock()
	defer fake.deregisterMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDependencyManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ groot.DependencyManager = new(FakeDependencyManager)
