# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.synced_folder '../', '/root/go/src/code.cloudfoundry.org/grootfs'
end
