// This file was generated by counterfeiter
package clonerfakes

import (
	"net/url"
	"sync"

	"code.cloudfoundry.org/grootfs/cloner"
	"code.cloudfoundry.org/lager"
)

type FakeFetcher struct {
	LayersDigestStub        func(logger lager.Logger, imageURL *url.URL) ([]cloner.LayerDigest, error)
	layersDigestMutex       sync.RWMutex
	layersDigestArgsForCall []struct {
		logger   lager.Logger
		imageURL *url.URL
	}
	layersDigestReturns struct {
		result1 []cloner.LayerDigest
		result2 error
	}
	StreamerStub        func(logger lager.Logger, imageURL *url.URL) (cloner.Streamer, error)
	streamerMutex       sync.RWMutex
	streamerArgsForCall []struct {
		logger   lager.Logger
		imageURL *url.URL
	}
	streamerReturns struct {
		result1 cloner.Streamer
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFetcher) LayersDigest(logger lager.Logger, imageURL *url.URL) ([]cloner.LayerDigest, error) {
	fake.layersDigestMutex.Lock()
	fake.layersDigestArgsForCall = append(fake.layersDigestArgsForCall, struct {
		logger   lager.Logger
		imageURL *url.URL
	}{logger, imageURL})
	fake.recordInvocation("LayersDigest", []interface{}{logger, imageURL})
	fake.layersDigestMutex.Unlock()
	if fake.LayersDigestStub != nil {
		return fake.LayersDigestStub(logger, imageURL)
	} else {
		return fake.layersDigestReturns.result1, fake.layersDigestReturns.result2
	}
}

func (fake *FakeFetcher) LayersDigestCallCount() int {
	fake.layersDigestMutex.RLock()
	defer fake.layersDigestMutex.RUnlock()
	return len(fake.layersDigestArgsForCall)
}

func (fake *FakeFetcher) LayersDigestArgsForCall(i int) (lager.Logger, *url.URL) {
	fake.layersDigestMutex.RLock()
	defer fake.layersDigestMutex.RUnlock()
	return fake.layersDigestArgsForCall[i].logger, fake.layersDigestArgsForCall[i].imageURL
}

func (fake *FakeFetcher) LayersDigestReturns(result1 []cloner.LayerDigest, result2 error) {
	fake.LayersDigestStub = nil
	fake.layersDigestReturns = struct {
		result1 []cloner.LayerDigest
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) Streamer(logger lager.Logger, imageURL *url.URL) (cloner.Streamer, error) {
	fake.streamerMutex.Lock()
	fake.streamerArgsForCall = append(fake.streamerArgsForCall, struct {
		logger   lager.Logger
		imageURL *url.URL
	}{logger, imageURL})
	fake.recordInvocation("Streamer", []interface{}{logger, imageURL})
	fake.streamerMutex.Unlock()
	if fake.StreamerStub != nil {
		return fake.StreamerStub(logger, imageURL)
	} else {
		return fake.streamerReturns.result1, fake.streamerReturns.result2
	}
}

func (fake *FakeFetcher) StreamerCallCount() int {
	fake.streamerMutex.RLock()
	defer fake.streamerMutex.RUnlock()
	return len(fake.streamerArgsForCall)
}

func (fake *FakeFetcher) StreamerArgsForCall(i int) (lager.Logger, *url.URL) {
	fake.streamerMutex.RLock()
	defer fake.streamerMutex.RUnlock()
	return fake.streamerArgsForCall[i].logger, fake.streamerArgsForCall[i].imageURL
}

func (fake *FakeFetcher) StreamerReturns(result1 cloner.Streamer, result2 error) {
	fake.StreamerStub = nil
	fake.streamerReturns = struct {
		result1 cloner.Streamer
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.layersDigestMutex.RLock()
	defer fake.layersDigestMutex.RUnlock()
	fake.streamerMutex.RLock()
	defer fake.streamerMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cloner.Fetcher = new(FakeFetcher)
