// This file was generated by counterfeiter
package image_clonerfakes

import (
	"sync"

	"code.cloudfoundry.org/grootfs/groot"
	"code.cloudfoundry.org/grootfs/store/image_cloner"
	"code.cloudfoundry.org/lager"
)

type FakeImageDriver struct {
	SnapshotStub        func(logger lager.Logger, fromPath, toPath string) error
	snapshotMutex       sync.RWMutex
	snapshotArgsForCall []struct {
		logger   lager.Logger
		fromPath string
		toPath   string
	}
	snapshotReturns struct {
		result1 error
	}
	ApplyDiskLimitStub        func(logger lager.Logger, path string, diskLimit int64, exclusive bool) error
	applyDiskLimitMutex       sync.RWMutex
	applyDiskLimitArgsForCall []struct {
		logger    lager.Logger
		path      string
		diskLimit int64
		exclusive bool
	}
	applyDiskLimitReturns struct {
		result1 error
	}
	FetchStatsStub        func(logger lager.Logger, path string) (groot.VolumeStats, error)
	fetchStatsMutex       sync.RWMutex
	fetchStatsArgsForCall []struct {
		logger lager.Logger
		path   string
	}
	fetchStatsReturns struct {
		result1 groot.VolumeStats
		result2 error
	}
	DestroyStub        func(logger lager.Logger, path string) error
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
		logger lager.Logger
		path   string
	}
	destroyReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImageDriver) Snapshot(logger lager.Logger, fromPath string, toPath string) error {
	fake.snapshotMutex.Lock()
	fake.snapshotArgsForCall = append(fake.snapshotArgsForCall, struct {
		logger   lager.Logger
		fromPath string
		toPath   string
	}{logger, fromPath, toPath})
	fake.recordInvocation("Snapshot", []interface{}{logger, fromPath, toPath})
	fake.snapshotMutex.Unlock()
	if fake.SnapshotStub != nil {
		return fake.SnapshotStub(logger, fromPath, toPath)
	} else {
		return fake.snapshotReturns.result1
	}
}

func (fake *FakeImageDriver) SnapshotCallCount() int {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	return len(fake.snapshotArgsForCall)
}

func (fake *FakeImageDriver) SnapshotArgsForCall(i int) (lager.Logger, string, string) {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	return fake.snapshotArgsForCall[i].logger, fake.snapshotArgsForCall[i].fromPath, fake.snapshotArgsForCall[i].toPath
}

func (fake *FakeImageDriver) SnapshotReturns(result1 error) {
	fake.SnapshotStub = nil
	fake.snapshotReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageDriver) ApplyDiskLimit(logger lager.Logger, path string, diskLimit int64, exclusive bool) error {
	fake.applyDiskLimitMutex.Lock()
	fake.applyDiskLimitArgsForCall = append(fake.applyDiskLimitArgsForCall, struct {
		logger    lager.Logger
		path      string
		diskLimit int64
		exclusive bool
	}{logger, path, diskLimit, exclusive})
	fake.recordInvocation("ApplyDiskLimit", []interface{}{logger, path, diskLimit, exclusive})
	fake.applyDiskLimitMutex.Unlock()
	if fake.ApplyDiskLimitStub != nil {
		return fake.ApplyDiskLimitStub(logger, path, diskLimit, exclusive)
	} else {
		return fake.applyDiskLimitReturns.result1
	}
}

func (fake *FakeImageDriver) ApplyDiskLimitCallCount() int {
	fake.applyDiskLimitMutex.RLock()
	defer fake.applyDiskLimitMutex.RUnlock()
	return len(fake.applyDiskLimitArgsForCall)
}

func (fake *FakeImageDriver) ApplyDiskLimitArgsForCall(i int) (lager.Logger, string, int64, bool) {
	fake.applyDiskLimitMutex.RLock()
	defer fake.applyDiskLimitMutex.RUnlock()
	return fake.applyDiskLimitArgsForCall[i].logger, fake.applyDiskLimitArgsForCall[i].path, fake.applyDiskLimitArgsForCall[i].diskLimit, fake.applyDiskLimitArgsForCall[i].exclusive
}

func (fake *FakeImageDriver) ApplyDiskLimitReturns(result1 error) {
	fake.ApplyDiskLimitStub = nil
	fake.applyDiskLimitReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageDriver) FetchStats(logger lager.Logger, path string) (groot.VolumeStats, error) {
	fake.fetchStatsMutex.Lock()
	fake.fetchStatsArgsForCall = append(fake.fetchStatsArgsForCall, struct {
		logger lager.Logger
		path   string
	}{logger, path})
	fake.recordInvocation("FetchStats", []interface{}{logger, path})
	fake.fetchStatsMutex.Unlock()
	if fake.FetchStatsStub != nil {
		return fake.FetchStatsStub(logger, path)
	} else {
		return fake.fetchStatsReturns.result1, fake.fetchStatsReturns.result2
	}
}

func (fake *FakeImageDriver) FetchStatsCallCount() int {
	fake.fetchStatsMutex.RLock()
	defer fake.fetchStatsMutex.RUnlock()
	return len(fake.fetchStatsArgsForCall)
}

func (fake *FakeImageDriver) FetchStatsArgsForCall(i int) (lager.Logger, string) {
	fake.fetchStatsMutex.RLock()
	defer fake.fetchStatsMutex.RUnlock()
	return fake.fetchStatsArgsForCall[i].logger, fake.fetchStatsArgsForCall[i].path
}

func (fake *FakeImageDriver) FetchStatsReturns(result1 groot.VolumeStats, result2 error) {
	fake.FetchStatsStub = nil
	fake.fetchStatsReturns = struct {
		result1 groot.VolumeStats
		result2 error
	}{result1, result2}
}

func (fake *FakeImageDriver) Destroy(logger lager.Logger, path string) error {
	fake.destroyMutex.Lock()
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
		logger lager.Logger
		path   string
	}{logger, path})
	fake.recordInvocation("Destroy", []interface{}{logger, path})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		return fake.DestroyStub(logger, path)
	} else {
		return fake.destroyReturns.result1
	}
}

func (fake *FakeImageDriver) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *FakeImageDriver) DestroyArgsForCall(i int) (lager.Logger, string) {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return fake.destroyArgsForCall[i].logger, fake.destroyArgsForCall[i].path
}

func (fake *FakeImageDriver) DestroyReturns(result1 error) {
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageDriver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	fake.applyDiskLimitMutex.RLock()
	defer fake.applyDiskLimitMutex.RUnlock()
	fake.fetchStatsMutex.RLock()
	defer fake.fetchStatsMutex.RUnlock()
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeImageDriver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ image_cloner.ImageDriver = new(FakeImageDriver)
