#!/bin/bash -e

ARGS=$@

if [ -d $ARGS ] &&
     [ "$(find $ARGS -maxdepth 1 -name '*_linux_test.go')" != "" ]; then
  fly -t lite execute -c ci/tasks/groot-tests.yml -p -i grootfs-git-repo="$PWD" -- $ARGS
else
  ginkgo -r -p $ARGS
fi
