// Code generated by counterfeiter. DO NOT EDIT.
package storefakes

import (
	"sync"

	"code.cloudfoundry.org/grootfs/store"
	"code.cloudfoundry.org/lager"
)

type FakeUnusedVolumeGetter struct {
	UnusedVolumesStub        func(lager.Logger, []string) ([]string, error)
	unusedVolumesMutex       sync.RWMutex
	unusedVolumesArgsForCall []struct {
		arg1 lager.Logger
		arg2 []string
	}
	unusedVolumesReturns struct {
		result1 []string
		result2 error
	}
	unusedVolumesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUnusedVolumeGetter) UnusedVolumes(arg1 lager.Logger, arg2 []string) ([]string, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.unusedVolumesMutex.Lock()
	ret, specificReturn := fake.unusedVolumesReturnsOnCall[len(fake.unusedVolumesArgsForCall)]
	fake.unusedVolumesArgsForCall = append(fake.unusedVolumesArgsForCall, struct {
		arg1 lager.Logger
		arg2 []string
	}{arg1, arg2Copy})
	fake.recordInvocation("UnusedVolumes", []interface{}{arg1, arg2Copy})
	fake.unusedVolumesMutex.Unlock()
	if fake.UnusedVolumesStub != nil {
		return fake.UnusedVolumesStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.unusedVolumesReturns.result1, fake.unusedVolumesReturns.result2
}

func (fake *FakeUnusedVolumeGetter) UnusedVolumesCallCount() int {
	fake.unusedVolumesMutex.RLock()
	defer fake.unusedVolumesMutex.RUnlock()
	return len(fake.unusedVolumesArgsForCall)
}

func (fake *FakeUnusedVolumeGetter) UnusedVolumesArgsForCall(i int) (lager.Logger, []string) {
	fake.unusedVolumesMutex.RLock()
	defer fake.unusedVolumesMutex.RUnlock()
	return fake.unusedVolumesArgsForCall[i].arg1, fake.unusedVolumesArgsForCall[i].arg2
}

func (fake *FakeUnusedVolumeGetter) UnusedVolumesReturns(result1 []string, result2 error) {
	fake.UnusedVolumesStub = nil
	fake.unusedVolumesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeUnusedVolumeGetter) UnusedVolumesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.UnusedVolumesStub = nil
	if fake.unusedVolumesReturnsOnCall == nil {
		fake.unusedVolumesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.unusedVolumesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeUnusedVolumeGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.unusedVolumesMutex.RLock()
	defer fake.unusedVolumesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUnusedVolumeGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ store.UnusedVolumeGetter = new(FakeUnusedVolumeGetter)
